-   id: deno-fmt
    name: deno fmt
    description: "Reformat using deno."
    language: node
    entry: deno
    additional_dependencies:
      - deno@1.3.0
    types_or: ["javascript", "jsx", "ts", "tsx", "markdown", "json"]
    args: ["fmt"]
    require_serial: true
-   id: deno-fmt-check
    name: deno fmt
    description: "Check formatting using deno."
    language: node
    entry: deno
    additional_dependencies:
      - deno@1.3.0
    types_or: ["javascript", "jsx", "ts", "tsx", "markdown", "json"]
    args: ["fmt", "--check"]
    require_serial: true
-   id: deno-lint
    name: deno lint
    description: "Lint and fix linting issues using deno."
    language: node
    entry: deno
    additional_dependencies:
      - deno@1.3.0
    types_or: ["javascript", "jsx", "ts", "tsx", "markdown", "json"]
    args: ["lint", "--fix"]
    require_serial: true
-   id: deno-lint-check
    name: deno lint
    description: "Lint check using deno."
    language: node
    entry: deno
    additional_dependencies:
      - deno@1.3.0
    types_or: ["javascript", "jsx", "ts", "tsx", "markdown", "json"]
    args: ["lint"]
    require_serial: true
