-   id: deno-fmt
    name: deno fmt
    language: node
    entry: deno
    additional_dependencies:
      - deno@1.43.6
    types_or: ["javascript", "ts", "markdown", "json"]
    args: ["fmt"]
-   id: deno-lint
    name: deno lint
    language: node
    entry: deno
    additional_dependencies:
      - deno@1.43.6
    types_or: ["javascript", "ts", "markdown", "json"]
    args: ["lint"]
