[package]
name = "deno-pre-commit"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde_json = "1.0.140"
regex = "1.11.1"
